apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: python-container
      image: python:3.9
      command: ["bash", "-c", "while true; do curl http://169.254.169.254/latest/meta-data/local-ipv4 > /mnt/ip-$(date +%s).txt; sleep 3600; done"]
      volumeMounts:
        - mountPath: /mnt
          name: ip-volume
    - name: sidecar-container
      image: busybox
      command: ["sh", "-c", "while true; do sleep 3600; done"]
      volumeMounts:
        - mountPath: /mnt
          name: ip-volume
  volumes:
    - name: ip-volume
      emptyDir: {}
